/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CHKB.UI;

import CHKB.DAO.ManipulationNhanVien;
import CHKB.MODAL.NhanVien;
import CHKB_DESIGN.MessageDialog;
import CHKB_DESIGN.ThongBao;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author caoho
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
//        làm form trong suốt
        setBackground(new Color(0,0,0,0));
        setLocationRelativeTo(null);
        btn_dangNhap.setRequestFocusEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRoundGradient1 = new CHKB_DESIGN.PanelRoundGradient();
        txt_tenDangNhap = new CHKB_DESIGN.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_dangNhap = new CHKB_DESIGN.ButtonGradient();
        txt_matKhau = new CHKB_DESIGN.PasswordField();
        ckb_hienThi = new CHKB_DESIGN.JCheckBoxCustom();
        jLabel5 = new javax.swing.JLabel();
        txt_minimize = new javax.swing.JLabel();
        txt_exit1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRoundGradient1.setColorEnd(new java.awt.Color(0, 0, 0, 120));
        panelRoundGradient1.setColorStart(new java.awt.Color(0, 0, 0, 120));
        panelRoundGradient1.setRoundBottomLeft(40);
        panelRoundGradient1.setRoundBottomRight(40);
        panelRoundGradient1.setRoundTopLeft(40);
        panelRoundGradient1.setRoundTopRight(40);

        txt_tenDangNhap.setForeground(new java.awt.Color(204, 0, 204));
        txt_tenDangNhap.setText("Cao Hoàng Khánh Băng");
        txt_tenDangNhap.setCaretColor(new java.awt.Color(255, 51, 204));
        txt_tenDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_tenDangNhap.setRound(40);
        txt_tenDangNhap.setSelectionColor(new java.awt.Color(204, 0, 102));
        txt_tenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenDangNhapActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Đăng nhập");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên đăng nhập");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mật khẩu");

        btn_dangNhap.setText("Đăng nhập");
        btn_dangNhap.setColor1(new java.awt.Color(255, 51, 204));
        btn_dangNhap.setColor2(new java.awt.Color(255, 204, 255));
        btn_dangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });

        txt_matKhau.setForeground(new java.awt.Color(255, 0, 204));
        txt_matKhau.setText("chkb");
        txt_matKhau.setCaretColor(new java.awt.Color(255, 0, 204));
        txt_matKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_matKhau.setRound(40);
        txt_matKhau.setSelectionColor(new java.awt.Color(255, 0, 153));

        ckb_hienThi.setBackground(new java.awt.Color(255, 51, 255));
        ckb_hienThi.setForeground(new java.awt.Color(255, 255, 255));
        ckb_hienThi.setText("Hiển thị mật khẩu");
        ckb_hienThi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ckb_hienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_hienThiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Quên mật khẩu?");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRoundGradient1Layout = new javax.swing.GroupLayout(panelRoundGradient1);
        panelRoundGradient1.setLayout(panelRoundGradient1Layout);
        panelRoundGradient1Layout.setHorizontalGroup(
            panelRoundGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundGradient1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(ckb_hienThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundGradient1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(panelRoundGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundGradient1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundGradient1Layout.createSequentialGroup()
                        .addGroup(panelRoundGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_dangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addGroup(panelRoundGradient1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(panelRoundGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addComponent(txt_tenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_matKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundGradient1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(239, 239, 239))))
        );
        panelRoundGradient1Layout.setVerticalGroup(
            panelRoundGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundGradient1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckb_hienThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_dangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(panelRoundGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 610, 450));

        txt_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CHKB_IMAGE/close.png"))); // NOI18N
        txt_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(txt_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, 30));

        txt_exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CHKB_IMAGE/remove.png"))); // NOI18N
        txt_exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_exit1MouseClicked(evt);
            }
        });
        getContentPane().add(txt_exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CHKB_IMAGE/login_background.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenDangNhapActionPerformed

    private void txt_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_minimizeMouseClicked
        this.setExtendedState(frmLogin.ICONIFIED);
    }//GEN-LAST:event_txt_minimizeMouseClicked

    private void txt_exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_exit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_txt_exit1MouseClicked

    private int xMouse, yMouse;
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xMouse = evt.getY();
        yMouse = evt.getX();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
//        setLocation(x+xMouse, y+yMouse);
//        setLocation(x, y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        String tenDangNhap = txt_tenDangNhap.getText().trim();
        String matKhau = new String(txt_matKhau.getPassword());
        if (tenDangNhap.length() < 1 || matKhau.length() < 1) {
//            JOptionPane.showConfirmDialog(null, "Vui lòng nhập đầy đủ các trường");
            ThongBao thongBao = new ThongBao(this);
            thongBao.showMessage("Cảnh báo", "Vui lòng nhập đầy đủ các trường");
        } else {
            try {
                ManipulationNhanVien ttnv = new ManipulationNhanVien();
                List<NhanVien> lstNhanVien = ttnv.getListNhanVien(tenDangNhap, matKhau);
                if (lstNhanVien.size() == 0) {
                    ThongBao thongBao = new ThongBao(this);
                    thongBao.showMessage("Thông báo", "Sai tên đăng nhập hoặc mật khẩu!!!");
                } else {
                    NhanVien nv = lstNhanVien.get(0);
                    if (ttnv.KiemTraVaiTro(nv) > 0) {
                        frmMain fm = new frmMain(nv);//nv.getHoTen(), nv.getVaiTro(), nv.getMaNhanVien()
                        this.dispose();
                        ThongBao thongBao = new ThongBao(this);
                        thongBao.showMessage("Thông báo", "Đăng nhập thành công");
                        fm.setVisible(true);
                    } else {
                        ThongBao thongBao = new ThongBao(this);
                        thongBao.showMessageSetIcon("Thông báo", "Bạn không đủ quyền để đăng nhập!!!", "/CHKB_IMAGE/warning_55.png");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_dangNhapActionPerformed

    private void ckb_hienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_hienThiActionPerformed
        if(ckb_hienThi.isSelected())
        {
            txt_matKhau.setEchoChar((char)0);
        }
        else
        {
            txt_matKhau.setEchoChar('*');
        }
    }//GEN-LAST:event_ckb_hienThiActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
         MessageDialog tb = new MessageDialog(this);
        tb.showMessage("Thông báo", "Bạn quên mật khẩu?\nChọn đặt lại để cập nhật mật khẩu hoặc thoát để tiếp tục đăng nhập", "Đặt lại", "Thoát", "/CHKB_IMAGE/warning_55.png");
        if (tb.getMessageType() == MessageDialog.MessageType.OK) {
            frmDatLaiMatKhau f = new frmDatLaiMatKhau();
            f.setVisible(true);
//            this.dispose();
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CHKB_DESIGN.ButtonGradient btn_dangNhap;
    private CHKB_DESIGN.JCheckBoxCustom ckb_hienThi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private CHKB_DESIGN.PanelRoundGradient panelRoundGradient1;
    private javax.swing.JLabel txt_exit1;
    private CHKB_DESIGN.PasswordField txt_matKhau;
    private javax.swing.JLabel txt_minimize;
    private CHKB_DESIGN.TextField txt_tenDangNhap;
    // End of variables declaration//GEN-END:variables
}
